name: 🚀 Feature Request
description: Request a new feature for the executive assistant
title: "[FEATURE] "
labels: ["type:feature", "stage:backlog", "priority:medium"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        Thank you for suggesting a new feature! This will help improve the executive assistant.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define the specific conditions that must be met for this feature to be considered complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Important for functionality
        - Critical - Blocking other work
      default: 1
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Any specific technical requirements or constraints
      placeholder: Framework requirements, performance targets, security considerations, etc.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request